input_trunk: "/home/moba/geno/HDGB-MoBaGenetics/2025.01.30_beta/moba_genotypes_2025.01.30_common"
release: "2025.09.16"
output_folder: "/home/oystein/hla_imputation_pipeout/"
hibag_model: "/home/oystein/InfiniumOmniExpress-24-European-HLA4-hg19.RData"
CookHLA_path: "/home/oystein/CookHLA"
from_bp: 28477895
to_bp: 34000000
CookHLA_mem: "58g"
allele_frequencies_folder: "/home/oystein/github/HLA-imputation/snakefiles/resources/norwegian_allele_frequencies"