input_trunk: "/home/RAW/4.MoBa_Genetics/MoBaPsychGen_v1/MoBaPsychGen_v1-ec-eur-batch-basic-qc"
release: "2026.10.06"
output_folder: "/home/oystein.kapperud/hla_imputation_pipeout/"
release_folder: "/home/oystein.kapperud/hla_imputation_release/"
CookHLA_path: "/home/oystein.kapperud/github/CookHLA"
HATK_path: "/home/oystein.kapperud/github/HATK"
IMGT_path: "/home/oystein.kapperud/github/IMGTHLA/"
IMGT_version: 3220
hg: 19
from_bp: 28477895
to_bp: 34000000
threads: 16
CookHLA_mem: "58g"
allele_frequencies_folder: "/home/oystein.kapperud/github/HLA-imputation/snakefiles/resources/norwegian_allele_frequencies/common/"